In [1]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
os.chdir('D:\\Data Science Batch 74\\Batch 74 Day 18\\CS 28 Random Forest Regression')

In [3]:
df=pd.read_csv('petrol_consumption.csv')
df.head(5)

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561
3,7.5,4870,2351,0.529,414
4,8.0,4399,431,0.544,410

In [4]:
df.isna().sum()

Petrol_tax                      0
Average_income                  0
Paved_Highways                  0
Population_Driver_licence(%)    0
Petrol_Consumption              0
dtype: int64

In [5]:
x=df.iloc[:,:-1]
x.head(5)

   Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)
0         9.0            3571            1976                         0.525
1         9.0            4092            1250                         0.572
2         9.0            3865            1586                         0.580
3         7.5            4870            2351                         0.529
4         8.0            4399             431                         0.544

In [6]:
y=df.iloc[:,-1]
y.head(2)

0    541
1    524
Name: Petrol_Consumption, dtype: int64

In [7]:
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [8]:
std=StandardScaler()
x=std.fit_transform(x)

In [9]:

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.25)
print ('X Shape-',x.shape)
print ('Y Shape-', y.shape)
print ('X_Train Shape-',x_train.shape)
print ('Y_Train Shape-',y_train.shape)
print ('X_Test Shape-',x_test.shape)
print ('Y_Test Shape-',y_test.shape)

X Shape- (48, 4)
Y Shape- (48,)
X_Train Shape- (36, 4)
Y_Train Shape- (36,)
X_Test Shape- (12, 4)
Y_Test Shape- (12,)

In [10]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()
dt=dt.fit(x,y)
dt

DecisionTreeRegressor()

In [11]:
y_pred=dt.predict(x)
y_pred

array([541., 524., 561., 414., 410., 457., 344., 467., 464., 498., 580.,
       471., 525., 508., 566., 635., 603., 714., 865., 640., 649., 540.,
       464., 547., 460., 566., 577., 631., 574., 534., 571., 554., 577.,
       628., 487., 644., 640., 704., 648., 968., 587., 699., 632., 591.,
       782., 510., 610., 524.])

In [12]:
accuracy=r2_score(y,y_pred)
print('Accuracy of Decision Tree Regressor is :',accuracy)

Accuracy of Decision Tree Regressor is : 1.0

In [13]:

from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y,y_pred)
mse

0.0

In [14]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor( n_estimators=15)
rf=rf.fit(x,y)

In [15]:
rf_ypred=rf.predict(x)
accuracy_rf=r2_score(y,rf_ypred)
print('Accuracy of Random forest Regressor is :',accuracy_rf)

Accuracy of Random forest Regressor is : 0.9118340587350998

In [16]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y,rf_ypred)
mse

1080.705925925926

In [17]:
rmse=np.sqrt(mse)
rmse

32.87409201675274

In [18]:
mse= np.square(np.subtract(y,rf_ypred)).mean() 
import math 
RMSE = math.sqrt(mse)
RMSE

32.87409201675274

In [21]:
aa=pd.concat([df,pd.DataFrame(rf_ypred,columns=["RF prediction"])],axis=1)
aa

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption,RF prediction
0,9.00,3571,1976,0.525,541,547.466667
1,9.00,4092,1250,0.572,524,539.666667
2,9.00,3865,1586,0.580,561,564.066667
3,7.50,4870,2351,0.529,414,435.600000
4,8.00,4399,431,0.544,410,463.666667
5,10.00,5342,1333,0.571,457,479.866667
6,8.00,5319,11868,0.451,344,392.466667
7,8.00,5126,2138,0.553,467,458.933333
8,8.00,4447,8577,0.529,464,471.933333
9,7.00,4512,8507,0.552,498,502.600000
10,8.00,4391,5939,0.530,580,564.533333
11,7.50,5126,14186,0.525,471,468.466667
12,7.00,4817,6930,0.574,525,533.133333
13,7.00,4207,6580,0.545,508,529.333333
14,7.00,4332,8159,0.608,566,579.200000
15,7.00,4318,10340,0.586,635,606.866667
16,7.00,4206,8508,0.572,603,600.533333
17,7.00,3718,4725,0.540,714,649.866667
18,7.00,4716,5915,0.724,865,790.400000
19,8.50,4341,6010,0.677,640,738.866667
20,7.00,4593,7834,0.663,649,706.333333
21,8.00,4983,602,0.602,540,512.600000
22,9.00,4897,2449,0.511,464,449.866667
23,9.00,4258,4686,0.517,547,543.866667
24,8.50,4574,2619,0.551,460,456.466667
25,9.00,3721,4746,0.544,566,552.666667
26,8.00,3448,5399,0.548,577,577.600000
27,7.50,3846,9061,0.579,631,617.600000
28,8.00,4188,5975,0.563,574,577.333333
29,9.00,3601,4650,0.493,534,532.000000
30,7.00,3640,6905,0.518,571,582.666667
31,7.00,3333,6594,0.513,554,560.133333
32,8.00,3063,6524,0.578,577,585.533333
33,7.50,3357,4121,0.547,628,602.733333
34,8.00,3528,3495,0.487,487,529.733333
35,6.58,3802,7834,0.629,644,637.866667
36,5.00,4045,17782,0.566,640,621.733333
37,7.00,3897,6385,0.586,704,634.133333
38,8.50,3635,3274,0.663,648,693.866667
39,7.00,4345,3905,0.672,968,877.266667
40,7.00,4449,4639,0.626,587,588.600000
41,7.00,3656,3985,0.563,699,687.866667
42,7.00,4300,3635,0.603,632,614.000000
43,7.00,3745,2611,0.508,591,601.533333
44,6.00,5215,2302,0.672,782,799.533333
45,9.00,4476,3942,0.571,510,521.000000
46,7.00,4296,4083,0.623,610,603.266667
47,7.00,5002,9794,0.593,524,531.066667

In [27]:
df_result=pd.concat([aa,pd.DataFrame(y_pred,columns=['DT prediction'])],axis=1)
df_result

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption,RF prediction,DT prediction
0,9.00,3571,1976,0.525,541,547.466667,541.0
1,9.00,4092,1250,0.572,524,539.666667,524.0
2,9.00,3865,1586,0.580,561,564.066667,561.0
3,7.50,4870,2351,0.529,414,435.600000,414.0
4,8.00,4399,431,0.544,410,463.666667,410.0
5,10.00,5342,1333,0.571,457,479.866667,457.0
6,8.00,5319,11868,0.451,344,392.466667,344.0
7,8.00,5126,2138,0.553,467,458.933333,467.0
8,8.00,4447,8577,0.529,464,471.933333,464.0
9,7.00,4512,8507,0.552,498,502.600000,498.0
10,8.00,4391,5939,0.530,580,564.533333,580.0
11,7.50,5126,14186,0.525,471,468.466667,471.0
12,7.00,4817,6930,0.574,525,533.133333,525.0
13,7.00,4207,6580,0.545,508,529.333333,508.0
14,7.00,4332,8159,0.608,566,579.200000,566.0
15,7.00,4318,10340,0.586,635,606.866667,635.0
16,7.00,4206,8508,0.572,603,600.533333,603.0
17,7.00,3718,4725,0.540,714,649.866667,714.0
18,7.00,4716,5915,0.724,865,790.400000,865.0
19,8.50,4341,6010,0.677,640,738.866667,640.0
20,7.00,4593,7834,0.663,649,706.333333,649.0
21,8.00,4983,602,0.602,540,512.600000,540.0
22,9.00,4897,2449,0.511,464,449.866667,464.0
23,9.00,4258,4686,0.517,547,543.866667,547.0
24,8.50,4574,2619,0.551,460,456.466667,460.0
25,9.00,3721,4746,0.544,566,552.666667,566.0
26,8.00,3448,5399,0.548,577,577.600000,577.0
27,7.50,3846,9061,0.579,631,617.600000,631.0
28,8.00,4188,5975,0.563,574,577.333333,574.0
29,9.00,3601,4650,0.493,534,532.000000,534.0
30,7.00,3640,6905,0.518,571,582.666667,571.0
31,7.00,3333,6594,0.513,554,560.133333,554.0
32,8.00,3063,6524,0.578,577,585.533333,577.0
33,7.50,3357,4121,0.547,628,602.733333,628.0
34,8.00,3528,3495,0.487,487,529.733333,487.0
35,6.58,3802,7834,0.629,644,637.866667,644.0
36,5.00,4045,17782,0.566,640,621.733333,640.0
37,7.00,3897,6385,0.586,704,634.133333,704.0
38,8.50,3635,3274,0.663,648,693.866667,648.0
39,7.00,4345,3905,0.672,968,877.266667,968.0
40,7.00,4449,4639,0.626,587,588.600000,587.0
41,7.00,3656,3985,0.563,699,687.866667,699.0
42,7.00,4300,3635,0.603,632,614.000000,632.0
43,7.00,3745,2611,0.508,591,601.533333,591.0
44,6.00,5215,2302,0.672,782,799.533333,782.0
45,9.00,4476,3942,0.571,510,521.000000,510.0
46,7.00,4296,4083,0.623,610,603.266667,610.0
47,7.00,5002,9794,0.593,524,531.066667,524.0

In [29]:
print("Completed")

Completed